### ISSUE TITLE
BUG - App from any branch does not load

### ISSUE THREAD

**Issue by chris-fady** [ADS2018UB/easyrider#42]
npm install exception but build successful
![image](https://user-images.githubusercontent.com/43273526/49962879-c38d9780-ff16-11e8-91c8-83247124d9fc.png)

Error triggered on localhost:
![image](https://user-images.githubusercontent.com/43273526/49962757-6691e180-ff16-11e8-8cdd-f7515c64c224.png)

**Comment by alhuelamo** [comment]
Do the tests with develop branch.
The warnings during `npm install` are not an issue.
The error in the page should be fixed in the latest commit.

I'm passing to you @chris-fady so you can verify and close the issue.

**Comment by chris-fady** [comment]
Checked and still the same issue. 
Might be linked to my config, don't know.

**Comment by alhuelamo** [comment]
Make sure you’re on commit e489e00.
I tried on a Windows machine and works.
Try removing `node_modules` folder and run again `npm install`

**Comment by jarandaf** [comment]
This is working on my side (develop branch).

**Comment by chris-fady** [comment]
Confirm working and closing, must have been a local issue - clone of develop launches the app
